apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: "http"
      nodePort: 30000
      targetPort: 8080
      protocol: TCP
  selector:
    app: dev-server
