# Default values for devapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 702401326258.dkr.ecr.us-east-1.amazonaws.com/devopsproj3
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 8080
