# Default values for devapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 608970462845.dkr.ecr.us-east-2.amazonaws.com/gercorri
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 8081
